logging: 
  file: ServiceLog/zCloudRestService-prod.log
  level: 
    root: debug

spring:
  thymeleaf: 
    cache: false
#    prefix: classpath:/templates/
    mode: LEGACYHTML5
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
    #定义初始连接数
#      initial-size: 10
    #定义最大连接数
#      maxActive: 20
    #定义最大空闲
      max_Idle: 20
    #定义最小空闲
#      minIdle: 1
    #定义最长等待时间
#    maxWait: 60000
    
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

jdbc:
  type: mysql
#公共配置与profiles选择无关
mybatis:
#  mapper-locations: classpath:com.xu.mapper/**.xml
  mapper-locations: classpath:mapping/*.xml
  mybatis.type-aliases-package: com.xu

  